# Generated by Django 2.2.2 on 2019-07-02 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0002_questionmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='asses_at',
            new_name='addes_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='question_like_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
