# Generated by Django 2.2.2 on 2019-07-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20190702_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionManager',
        ),
    ]
